#!/usr/bin/env python3
"""Embed the engine's Python source into the wasm module as a C string.

The web build has no filesystem, so the engine cannot be a file next to the
binary; and fetching it separately would be a second request for 100 KB that
compresses to a fraction of the wasm it sits beside. So it is compiled in.

Emitted as an array of octal escapes rather than as readable text, because the
source contains quotes, backslashes and trigraph-adjacent sequences, and the
one thing worse than an ugly generated header is a subtly mis-escaped one. C99
caps a string literal at 4095 characters, so the body is chunked into adjacent
literals, which the compiler concatenates.
"""
import sys
from pathlib import Path

CHUNK = 200          # source bytes per emitted literal; x4 for the escapes


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: embed_engine.py <DUUM.PY> <out.h>", file=sys.stderr)
        return 2
    src = Path(sys.argv[1])
    out = Path(sys.argv[2])
    data = src.read_bytes()
    if not data:
        print(f"embed_engine: {src} is empty", file=sys.stderr)
        return 1

    lines = [
        "/* GENERATED by ports/web/embed_engine.py - do not edit. */",
        f"/* source: {src.name}, {len(data)} bytes */",
        "#ifndef DUUM_ENGINE_SRC_H",
        "#define DUUM_ENGINE_SRC_H",
        "",
        "static const char DUUM_SRC[] =",
    ]
    for i in range(0, len(data), CHUNK):
        piece = "".join("\\%03o" % b for b in data[i:i + CHUNK])
        lines.append(f'    "{piece}"')
    lines += [";", "", "#endif", ""]

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="ascii")
    print(f"embed_engine: {len(data)} bytes -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
